# Generated by Django 5.2.4 on 2026-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projetblog',
            name='etat',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_analyse', 'En analyse')], default='en_cours', max_length=20),
        ),
        migrations.AddField(
            model_name='projetblog',
            name='langages',
            field=models.CharField(default='', help_text='Entrez les langages séparés par des virgules (ex: Python, Django, HTML)', max_length=500),
        ),
        migrations.AddField(
            model_name='projetblog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
    ]
