# Generated by Django 5.2.4 on 2026-02-20 11:15

import mon_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0003_projetblog_created_at_projetblog_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mon_app.models.upload_to_projet),
        ),
    ]
